# Generated by Django 5.0.3 on 2024-04-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.FileField(blank=True, null=True, upload_to='banner')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
